POST https://aiworkflow.cairns.co.za/api/workflow.php HTTP/1.1
content-type: application/json

{
    "name": "New Sample Workflow",
    "description": "This is a sample workflow",
    "created_by": "WilliamCairns"
}